In [ ]:
URK21CS1004                                                          12/07/2023

In [ ]:
AIM: To execute the basic data structures in Python.

In [ ]:
DESCRIPTION:
        
    Dictionary:
    In Python, a dictionary is a data structure that stores pairs of values, known as key-value pairs. It is created by enclosing a sequence of elements within curly braces {} and separating them with commas. The key in the key-value pair acts as the unique identifier, and the corresponding value represents the associated data.
    
    List:
    Lists are a built-in data type in Python used to store multiple items in a single variable. They allow storing elements of different data types and are denoted by square brackets [].
    
    Set:
    A set is an unordered collection data type in Python that is iterable, mutable, and does not allow duplicate elements. Sets are defined using curly braces {}.
    
    Tuple:
    A tuple is similar to a list in terms of indexing and nested objects, but unlike lists, tuples are immutable, meaning their elements cannot be changed after creation. Tuples are defined using parentheses ().

    NumPy:
    NumPy is a powerful library in Python used for array processing and scientific computing. It provides a high-performance multidimensional array object called numpy.ndarray.
    
    .csv files:
    To read or access .csv files in Python, we need to use the csv library. This library provides functionalities to work with comma-separated value (CSV) files.

In [ ]:
PROGRAM:

In [1]:
import pandas as pd

In [ ]:
1. Create an empty dictionary and fill with some sub_code and sub_name as pair by user input. Then take one sub_code as input from the user and traverse through dictionary to find the corresponding sub_name and display the same.

In [2]:
print("BISWAYAN MEHRA \nURK21CS1004")
subject_dict = {}
num_subjects = int(input("Enter the number of subjects you want to add: "))
for _ in range(num_subjects):
    sub_code = input("Enter subject code: ")
    sub_name = input("Enter subject name: ")
    subject_dict[sub_code] = sub_name

sub_code_to_find = input("Enter the subject code to find its name: ")
sub_name = subject_dict.get(sub_code_to_find)
if sub_name is not None:
    print(f"The subject name for code {sub_code_to_find} is: {sub_name}")
else:
    print(f"Subject code {sub_code_to_find} not found in the dictionary.")

BISWAYAN MEHRA 
URK21CS1004


Enter the number of subjects you want to add:  2
Enter subject code:  2004
Enter subject name:  Maths
Enter subject code:  2006
Enter subject name:  Physics
Enter the subject code to find its name:  2006


The subject name for code 2006 is: Physics


In [ ]:
2. Create an empty list and fill with list of words by user input. Find the list of words that are longer than n from a given list of words.

In [3]:
print("BISWAYAN MEHRA \nURK21CS1004")
word_list = []
n = int(input("Enter n: "))
num_words = int(input("Enter the number of words: "))
for i in range(num_words):
    word = input(f"Enter word {i+1}: ")
    word_list.append(word)
longer_than_n = [word for word in word_list if len(word) > n]
print("Words longer than", n, "are:", longer_than_n)

BISWAYAN MEHRA 
URK21CS1004


Enter n:  3
Enter the number of words:  4
Enter word 1:  the
Enter word 2:  quick
Enter word 3:  brown
Enter word 4:  fox


Words longer than 3 are: ['quick', 'brown']


In [ ]:
3. Create an empty set and fill with some values by user input. Check if a given value is present in a set or not.

In [4]:
print("BISWAYAN MEHRA \nURK21CS1004")
value_set = set()
num_values = int(input("Enter the number of values: "))
for i in range(num_values):
    value = input(f"Enter value {i+1}: ")
    value_set.add(value)
value_to_check = input("Enter the value to check: ")
if value_to_check in value_set:
    print(f"{value_to_check} is present in the set.")
else:
    print(f"{value_to_check} is NOT present in the set.")

BISWAYAN MEHRA 
URK21CS1004


Enter the number of values:  4
Enter value 1:  50
Enter value 2:  10
Enter value 3:  60
Enter value 4:  50
Enter the value to check:  50


50 is present in the set.


In [ ]:
4. Create an empty tuple and fill with some values by user input. Count the occurrence of a given input number in the tuple.

In [5]:
print("BISWAYAN MEHRA \nURK21CS1004")
value_tuple = ()
num_values = int(input("Enter the number of values: "))
for i in range(num_values):
    value = int(input(f"Enter value {i+1}: "))
    value_tuple += (value,)
number_to_count = int(input("Enter n: "))
count_occurrences = value_tuple.count(number_to_count)
print(f"The number {number_to_count} appears {count_occurrences} times in the tuple.")

BISWAYAN MEHRA 
URK21CS1004


Enter the number of values:  4
Enter value 1:  50
Enter value 2:  10
Enter value 3:  60
Enter value 4:  50
Enter n:  50


The number 50 appears 2 times in the tuple.


In [ ]:
5. Create a 2D array and perform matrix subtraction using numpy.

In [6]:
print("BISWAYAN MEHRA \nURK21CS1004")
import numpy as np
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result_matrix = matrix1 - matrix2
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult:")
print(result_matrix)

BISWAYAN MEHRA 
URK21CS1004
Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
6. Read an .csv file and display the basic details.

In [7]:
print("BISWAYAN MEHRA \nURK21CS1004")
df = pd.read_csv("Heart.csv")
print(df)

BISWAYAN MEHRA 
URK21CS1004
     Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope  Ca     

In [ ]:
RESULT: Thus, the python programs using data structures were executed and verified successfully.