In [ ]:
1. Create an empty dictionary and fill with some sub_code and sub_name as pair by user
input. Then take one sub_code as input from the user and traverse through dictionary
to find the corresponding sub_name and display the same.

In [3]:
dic = dict([m.split(":") for m in input("Enter key:value ").split()])
search = input("Enter search sub_code: ")
if search in dic:
    print("sub_name: ",dic[search])

Enter key:value  1:History 2:Maths 3:English
Enter search sub_code:  2


sub_name:  Maths


In [ ]:
2. Create an empty list and fill with list of words by user input. Find the list of words that
are longer than n from a given list of words.
Sample List : [‘the’,’quick’,’brown’,’fox’]
n : 3
Expected Result : quick brown

In [12]:
ls = [x for x in input("Enter elements: ").split()]
n = int(input("Enter length:"))
print([x for x in ls if len(x) > n])

Enter elements:  the quick brown fox
Enter length: 3


['quick', 'brown']


In [ ]:
3. Create an empty set and fill with some values by user input. Check if a given value is
present in a set or not.

In [19]:
if int(input("Enter search value: ")) in set([int(x) for x in input("Enter values: ").split()]):
    print("Value Exists.")
else:
    print("Value NOT Exists.")

Enter search value:  10
Enter values:  1 2 3 4 5 6 7 8 9 0


Value NOT Exists.


In [ ]:
4. Create an empty tuple and fill with some values by user input. Count the occurrence of
a given input number in the tuple.
Sample : (50, 10, 60, 70, 50)
n : 50
Expected Result : 2

In [22]:
t = tuple([int(x) for x in input('Enter values: ').split()])
n = int(input("Enter search value: "))
print(t.count(n))

Enter values:  50 10 60 70 50
Enter search value:  50


2


In [ ]:
5. Create a 2D array and perform matrix subtraction using numpy.

In [28]:
import numpy as np
arr1 = np.array([[int(y) for y in x.split()] for x in input("Enter data: ").split("  ")])
arr2 = np.array([[int(y) for y in x.split()] for x in input("Enter data: ").split("  ")])
print(arr1-arr2)

Enter data:  1 2 3  4 5 6  7 8 9
Enter data:  9 8 7  6 5 4  3 2 1


[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
6. Read an .csv file and display the basic details.

In [30]:
import os
import pandas as pd
os.chdir('C:/Users/mehra/Codes/KITS/SEM 5/Intro to Data Science/LAB/LAB EXAM PREP/DataSets/')
df = pd.read_csv('Heart.csv')
df.head(2)

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   

   ExAng  Oldpeak  Slope  Ca    Thal  AHD  
0      0      2.3      3   0   fixed   No  
1      1      1.5      2   3  normal  Yes